### PR TITLE
Copy ABOUT.md in Dockerfile

### LINKED ISSUE #784: Dockerfile does not build, missing ABOUT.md
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + commit 61b63e9b549b4ae92796b5595f583e4cff388a13
* Environment name and version:
  + Node.js version v10.1.0
    - Docker image node 10.1-alpine
  + npm version 5.6.0
  + Web browser N/A
* Operating System and version:
  + Debian 9
  + Docker version 18.09.5, build e8ff056dbc 

## Summary
Docker image fails to build in Step 12, due to required file `ABOUT.md` not being a part of the COPY steps and not being present for the build:

```
Step 12/21 : RUN npm run build &&     npm prune --production
 ---> Running in cdd2bdc9e83f

> flood@1.0.0 build /usr/src/app
> node client/scripts/build.js

(node:17) ExperimentalWarning: The fs.promises API is experimental
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../../../../../../ABOUT.md' in '/usr/src/app/client/src/javascript/components/modals/settings-modal'
```

The include is in file `client/src/javascript/components/modals/settings-modal/AboutTab.js`

## Possible Solution

Include ABOUT.md in build.

## Steps to Reproduce

1. `docker build .`

### PR DESCRIPTION
**Pull request by bbashy**
## Description
ABOUT.md was not copied for the Docker image.

## Related Issue
Fixes #784

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by baurmatt** [comment]
I would argue that a ABOUT.md file does not belong in a production Docker container.

**Comment by bbashy** [comment]
@baurmatt Maybe just reference raw git file in axios request?

**Comment by jeanralphaviles** [comment]
I cloned this PR and built the Docker image, but the about page renders empty. Not sure if it's an issue with this PR or #727 

```bash
git clone https://github.com/Flood-UI/flood.git
cd flood
git fetch origin pull/786/head
git checkout FETCH_HEAD 
docker build -t flood:latest .
docker run --rm -p 3000:3000 flood:latest
```

image

**Comment by bbashy** [comment]
@jeanralphaviles Anything in logs?

**Comment by jeanralphaviles** [comment]
Not much

GET /static/media/ABOUT.24e8abcd.md 304

https://gist.github.com/jeanralphaviles/d759541569fa643309591dc80eefe4fa

**Comment by mirolm** [comment]
It breaks the same way in no-docker build too.

Error message is:

``AboutTab.js:16 Uncaught (in promise) TypeError: e.text is not a function
    at AboutTab.js:16``

**Comment by jfurrow** [comment]
I just pushed [a fix](https://github.com/Flood-UI/flood/commit/3f76d267fa9dcc1b50872e7c429febd280f15b88) upstream which should make this work

**Pull request merged**
